---
# tasks file for ansible-oracle-java8
- import_tasks: debian.yml
  when: ansible_os_family is defined and ansible_os_family == "Debian"

- import_tasks: windows.yml
  when: ansible_os_family is defined and ansible_os_family == "Windows"
